sudo: false
language: node_js
node_js:
- '0.12'
- '0.10'
before_script:
- npm install -g jscs
script:
- npm run-script jshint
- npm run-script jscs
- npm test
after_script:
- npm run-script coveralls
deploy:
- provider: npm
  email: austin@austinpray.com
  api_key:
    secure: bRoYXumnzrnjQXZHhsFDDAJgDklgceFS6NmzBIqUuubrulg5SDvCIEZ+rXFSgSKcBSG1ebU+3pa/IrlG3TaAS3uQeT4brvl+ChReub+0oAJjn7e8w62Oyso8kengyi6J4r0FaAC4jNjQ8KUxnxIkFHcyWr4hr5AEIy3PXXQHG4Q=
  on:
    tags: true
    repo: austinpray/asset-builder-cli
    all_branches: true
    node: '0.12'
